ALTER TABLE "Book" ADD COLUMN "olWorkId" TEXT;
ALTER TABLE "Book" ADD COLUMN "olRatingAvg" DOUBLE PRECISION;
ALTER TABLE "Book" ADD COLUMN "olRatingCount" INTEGER;
ALTER TABLE "Book" ADD COLUMN "olFetchedAt" TIMESTAMP(3);
